<!doctype html>
<html lang="en" class="no-js">
<head>
  <meta charset="utf-8">
  <!--[if IE]><![endif]-->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Ployee</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="stylesheet" href="/css/style.css?v=1">
  <script src="/js/modernizr-1.6.min.js?v=1"></script>
</head>
<!--[if lt IE 7 ]> <body class="ie6 no-js"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie7 no-js"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie8 no-js"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie9 no-js"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <body class="no-js"> <!--<![endif]-->

  <div id="container">
    <header>
      <h1>Ployee</h1>
      <h2>Velg ditt ansattbilde!</h2>
    </header>
    
    <div id="main">
      <?php echo $this->layout()->content; ?>
    </div>
    
    <footer>
      
    </footer>
  </div> <!-- end of #container -->

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <script>!window.jQuery && document.write('<script src="js/jquery-1.4.2.min.js"><\/script>')</script>
  <script src="/js/plugins.js?v=1"></script>
  <script src="/js/script.js?v=1"></script>

  <!--[if lt IE 7 ]>
    <script src="/js/dd_belatedpng.js?v=1"></script>
  <![endif]-->
</body>
</html>